applicationsets:
  main:
    name: main
    generators:
      - git:
          repoURL: https://github.com/techgardencode/argo-cd-aoe.git
          revision: main
          directories:
            - path: "kubernetes/argocd/**/overlays/5963"
            - path: "kubernetes/default/**/overlays/5963"
            - path: "kubernetes/external-dns/**/overlays/5963"
            - path: "kubernetes/ingress-nginx/**/overlays/5963"
            - path: "kubernetes/cert-manager/**/overlays/5963"
    template:
      metadata:
        name: "{{path[1]}}-{{path[2]}}-{{path.basenameNormalized}}"
        project: default
        source:
          repoURL: https://github.com/techgardencode/argo-cd-aoe.git
          targetRevision: main
          path: "{{path}}"
          plugin:
            name: kustomize-helm
            parameters:
              - name: NAMESPACE
                string: "{{path[1]}}"
        destination:
          name: in-cluster
          namespace: "{{path[1]}}"
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
