apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

helmCharts:
  - name: hello-world
    version: 0.1.0
    releaseName: hello-world
    repo: https://helm.github.io/examples
    namespace: default
