apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

helmGlobals:
  chartHome: ../../../../../helm-charts

helmCharts:
  - name: generic-service
    releaseName: kian-coffee
    valuesFile: ../../base
    namespace: default
    additionalValuesFiles:
      - values.yaml
