grafana:
  ingress:
    enabled: true
    ingressClassName: ingress-nginx-private
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: grafana.1276.kian.sh
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.1276.kian.sh
