image:
  repository: "ghcr.io/techgardencode/kian.coffee"
  tag: "c8d7408498dcf1d638c19f54e5fa4c36a6a5af72"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: coffee.kian.sh
  tls:
    secretName: kian-coffee-tls
