image:
  repository: "ghcr.io/techgardencode/kian.coffee"
  tag: "b4dcf5329dad0e247942acae8e06e6dc6352ee38"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: coffee.kian.sh
  tls:
    secretName: kian-coffee-tls
