image:
  repository: "ghcr.io/techgardencode/kian.coffee"
  tag: "7179c270e400c72ebb803778eb3932cef5a5c2e6"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: coffee.kian.sh
  tls:
    secretName: kian-coffee-tls
