applicationsets:
  main:
    name: main
    generators:
      - git:
          repoURL: https://github.com/techgardencode/argo-cd-aoe.git
          revision: main
          directories:
            - path: "kubernetes/**/_namespace"
            - path: "kubernetes/argocd/**/base"
            - path: "kubernetes/default/**/base"
            - path: "kubernetes/external-dns/**/base"
    template:
      metadata:
        name: "{{path[1]}}-{{regexReplaceAll '_' path[2] ''}}-{{path.basenameNormalized}}"
        project: default
        source:
          repoURL: https://github.com/techgardencode/argo-cd-aoe.git
          targetRevision: main
          path: "{{path}}"
          plugin:
            name: kustomize-helm
            parameters:
              - name: NAMESPACE
                string: "{{path[1]}}"
        destination:
          name: in-cluster
          namespace: "{{path[1]}}"
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
