apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../../base

helmCharts:
  - repo: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 69.3.2
    releaseName: prometheus
    includeCRDs: true
    valuesFile: ../../base/values.yaml
    namespace: monitoring
    additionalValuesFiles:
      - values.yaml
