
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kian-coffee-app-dev
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/techgardencode/kian.coffee.git
    path: charts/overlays/dev
    targetRevision: HEAD
    plugin:
      name: kustomized-helm
