argo-cd:
    application:
        namespaces: "*"
    applicationSet:
        replicas: 2
    configs:
        cmp:
            create: true
            plugins: |
                apiVersion: argoproj.io/v1alpha1
                kind: ConfigManagementPlugin
                metadata:
                    name: kustomized-helm
                spec:
                    version: v1.0
                    init:
                        command: ["/bin/sh", "-c"]
                        args: ["helm dependency build"]
                    generate:
                        command: ["/bin/sh", "-c"]
                        args:
                            [
                                "helm template . --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE --kube-version $KUBE_VERSION > all.yaml && kustomize build",
                            ]
    controller:
        replicas: 1
    global:
        domain: argocd.1276.kian.sh
    redis-ha:
        enabled: true
    repoServer:
        replicas: 2
    server:
        replicas: 2
        service:
            type: LoadBalancer
        ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-production"
                nginx.ingress.kubernetes.io/ssl-passthrough: "true"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            tls: true
