image:
  repository: "ghcr.io/techgardencode/www"
  tag: "latest@sha256:be50685b531a961c0d141b005fd88835de3d587e07f0d900153767966dd926ac"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: techgarden.kian.sh
  tls:
    secretName: techgarden-gg-tls
