image:
  repository: "ghcr.io/techgardencode/www"
  tag: "7cdbb3cd5d83fba900b6e5d6c7436532388aa702"

ports:
  - name: main
    containerPort: 80

service:
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: techgarden.kian.sh
  tls:
    secretName: techgarden-gg-tls
