---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-forward
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-connections: "10"
    nginx.ingress.kubernetes.io/limit-rps: "15"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  namespace: tools
spec:
  ingressClassName: ingress-nginx-private
  rules:
    - host: ha.1276.kian.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant-forward
                port:
                  number: 8123
  tls:
    - hosts:
         - ha.1276.kian.sh
      secretName: home-assistant-tls
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-forward
  namespace: tools
spec:
  type: ExternalName
  externalName: 10.0.60.26
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
