policy: sync
registry: txt
txtPrefix: _external-dns-
txtOwnerId: kian

# extraArgs:
#   - "--ingress-class=ingress-nginx-public"

provider:
  name: cloudflare

sources:
  - service
  - ingress
  - crd

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey
