apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - ../../base
  - templates/ingress.yaml

helmCharts:
  - name: hello-world
    version: 0.1.0
    releaseName: hello-world
    repo: https://helm.github.io/examples
    namespace: external-dns
    additionalValuesFiles:
      - values.yaml
