apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../../base

helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: loki-stack
    version: 2.9.3
    releaseName: loki
    includeCRDs: false
    valuesFile: ../../base/values.yaml
    namespace: monitoring
    additionalValuesFiles:
      - values.yaml
